;;; xterm-keybinder-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xterm-keybinder.el

(autoload 'xterm-keybinder-setup "xterm-keybinder" "\
Enable Emacs keybinds even in the xterm terminal Emacs." t)
(autoload 'urxvt-keybinder-insert "xterm-keybinder" "\
Insert urxvt setting." t)
(autoload 'urxvt-change-font-size "xterm-keybinder" "\
Change font size in URxvt.

OFFSET is a variable to increase/decrease the font size from
current font size.

Optional variable FONT is the font name and as the default value,
this functions uses the value that you will set in
‘urxvt-keybinder-setup’.

If you set optional ABSOLUTE-SIZE variable, this function priors
the size than OFFSET and sets the ABSOLUTE-SIZE.

(fn OFFSET &optional FONT ABSOLUTE-SIZE)")
(autoload 'urxvt-keybinder-setup "xterm-keybinder" "\
Setup function for URxvt.
You can also set FONT name and the SIZE.

If you set BOTH FONT and SIZE, you can use ‘text-scale-increase’
and ‘text-scale-decrease’ functions to adjust font size inside
URxvt frame.

(fn &optional FONT SIZE)")
(register-definition-prefixes "xterm-keybinder" '("urxvt-font-" "xterm-keybinder-"))

;;; End of scraped data

(provide 'xterm-keybinder-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xterm-keybinder-autoloads.el ends here
